### PR TITLE
Interested in using Material Design for this?

### PR DESCRIPTION
**Pull request by ButchersBoy**
Threw together a quick hack to illustrate:

image

### CODE REVIEW

**Comment by Codeusa** [comment]
Material design does look much nicer than the standard form design, if you want to implement it I'll gladly accept the pull.

**Comment by ButchersBoy** [comment]
:cool:  I'll try and tidy it up over the weekend.

**Comment by Thristle** [comment]
this means moving to WFP doesn't it? its a newer standard and thus feel more "natural".
however, if Codeusa have no experience in WFP it might be hard for him to continue development without first acquiring the skills

**Comment by ButchersBoy** [comment]
...sorry yeah...it's WPF...

Although the code is pretty clean and straight forward and the existing form isn't to complex, so I reckon could be done without too much fuss.

Just let me know if you want to carry on, or I can fix up the pull request and you can take a look at the code.

**Comment by ButchersBoy** [comment]
@Codeusa OK, see what you think.  Visually, I can still tidy up a bit, but at this stage it switches it from WinForms to WPF and all the existing functionality is plugged in.

Basically, MainWindow and MainWindowViewModel replace Form1, and everything else is the same.  There's a few extra files to support WPF and Material Design Theme.

If you accept this PR I'd have to make a second PR to go in and remove the WinForms completely, and I could add a progress bar etc.

steamcleanerwpf

**Comment by ButchersBoy** [comment]
P.S make sure to restore the nuget package

**Comment by Codeusa** [comment]
@ButchersBoy i've read over everything and it all looks straight forward, nothing outrageous to learn. 

Submit a new pull with all the final changes and I'll accept that after review.

**Comment by ButchersBoy** [comment]
Moving to new PR as requested.

**Pull request closed without merging**
